version: '3.9'

services:
    developers-levels:
        build: .
        ports:
            - 3000:3000

    mysql:
        image: mysql:5.7
        volumes:
            - gazin-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: gazin

volumes:
    gazin-mysql-data:
